links = [{'title': 'dining chair', 'link': 'https://nagarey.com/shop/furnitur-kursi', 'category': ['ruang makan']},
{'title': 'upholstered chair', 'link': 'https://nagarey.com/shop/furnitur-kursi-lapis-busa', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'dining / work desk table', 'link': 'https://nagarey.com/shop/furnitur-meja-makan-kerja', 'category': ['ruang makan']},
{'title': 'bench and stool', 'link': 'https://nagarey.com/shop/furnitur-bangku-bangku-panjang', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'bar stool', 'link': 'https://nagarey.com/shop/furnitur-kursi-bar', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'lounge chair', 'link': 'https://nagarey.com/shop/furnitur-kursi-santai', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'sofa', 'link': 'https://nagarey.com/shop/furnitur-sofa', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'coffee / side table', 'link': 'https://nagarey.com/shop/furnitur-meja-tengah-samping', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'outdoor', 'link': 'https://nagarey.com/shop/furnitur-luar-ruangan', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'cabinet and console', 'link': 'https://nagarey.com/shop/furnitur-kabinet-konsol', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'timber / antique wood', 'link': 'https://nagarey.com/shop/furnitur-kayu-antik-gelondong', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'clothes and shoe rack', 'link': 'https://nagarey.com/shop/furnitur-rak-sepatu-pakaian', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'ladder', 'link': 'https://nagarey.com/shop/furnitur-tangga', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'bed and headboard', 'link': 'https://nagarey.com/shop/furnitur-ranjang-dipan', 'category': ['kamar tidur']},
{'title': 'daybed ', 'link': 'https://nagarey.com/shop/furnitur-ranjang-santai', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'screen / divider', 'link': 'https://nagarey.com/shop/furnitur-sekat-pemisah', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'children and baby', 'link': 'https://nagarey.com/shop/furnitur-mebel-anak-bayi', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'candleholder and terrarium', 'link': 'https://nagarey.com/shop/dekorasi-tempat-lilin-terrarium', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'decorative object', 'link': 'https://nagarey.com/shop/dekorasi-objek-dekorasi', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'tray and display box', 'link': 'https://nagarey.com/shop/dekorasi-baki-kotak-pajang', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'rug', 'link': 'https://nagarey.com/shop/karpet-bantal-karpet', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'natural rug', 'link': 'https://nagarey.com/shop/karpet-bantal-karpet-bahan-tanaman', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'animal rug and throw', 'link': 'https://nagarey.com/shop/karpet-bantal-karpet-selimut-hewan', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'seating cushion', 'link': 'https://nagarey.com/shop/karpet-bantal-bantal-duduk', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'cushion', 'link': 'https://nagarey.com/shop/karpet-bantal-bantal', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'basket', 'link': 'https://nagarey.com/shop/keranjang-boks-keranjang', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'box / organizer', 'link': 'https://nagarey.com/shop/keranjang-boks-boks-organizer', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'laundry basket', 'link': 'https://nagarey.com/shop/keranjang-boks-keranjang-cucian', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'decorative / large basket', 'link': 'https://nagarey.com/shop/keranjang-boks-keranjang-besar-dekoratif', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'placemat', 'link': 'https://nagarey.com/shop/utensil-dapur-placemat', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'serving tray', 'link': 'https://nagarey.com/shop/utensil-dapur-serving-tray', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'cake stand', 'link': 'https://nagarey.com/shop/utensil-dapur-cake-stand-dome', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'serving plate', 'link': 'https://nagarey.com/shop/utensil-dapur-serving-plate', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'dinnerware', 'link': 'https://nagarey.com/shop/utensil-dapur-dinnerware', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'island table and kitchen furniture', 'link': 'https://nagarey.com/shop/utensil-dapur-kitchen-furnitures', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'clock', 'link': 'https://nagarey.com/shop/hiasan-dinding-jam-cermin-jam-dinding', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'modern prints', 'link': 'https://nagarey.com/shop/hiasan-dinding-jam-cermin-gambar-print-modern', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'classic / vintage print', 'link': 'https://nagarey.com/shop/hiasan-dinding-jam-cermin-gambar-print-klasik', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'wall object', 'link': 'https://nagarey.com/shop/hiasan-dinding-jam-cermin-hiasan-dinding', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'mirror', 'link': 'https://nagarey.com/shop/hiasan-dinding-jam-cermin-cermin', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'black and white prints', 'link': 'https://nagarey.com/shop/hiasan-dinding-jam-cermin-foto-hitam-putih', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'japanese ukiyo', 'link': 'https://nagarey.com/shop/hiasan-dinding-jam-cermin-lukisan-ukiyo-jepang', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'Lighting', 'link': 'https://nagarey.com/shop/lampu', 'category': ['ruang keluarga', 'ruang tamu', 'kamar tidur']},
{'title': 'vase', 'link': 'https://nagarey.com/shop/vas-tanaman-vas', 'category': ['ruang keluarga', 'ruang tamu', 'kamar tidur']},
{'title': 'planters', 'link': 'https://nagarey.com/shop/vas-tanaman-tempat-tanaman', 'category': ['ruang keluarga', 'ruang tamu']},
{'title': 'pet bed', 'link': 'https://nagarey.com/shop/peliharaan-pet-bed', 'category': ['ruang keluarga', 'ruang tamu', 'kamar tidur']},
]